#   Find average PPN for each city

#  Find average PPN for each city

# Find average PPN for each city

In [10]:
import pandas as pd

In [11]:
file_path = "/home/nineleaps/Downloads/cap_rooms.csv"

In [12]:
df = pd.read_csv(file_path)

In [13]:
df

,ID,City,Location,PType,PPN,Nights,Beds,Baths,Reviews,Recent
0,IND137,Mumbai,NaN,Entire Home/Apartment,"₹3,200",2.0,1.0,1.0,4.0,2022-03-12
1,IND138,Bangalor,Indiranagar,Private Room,1800,NaN,1.0,1.0,2.0,15-Feb-23
2,IND139,Delhi,Hauz Khas,Entire Home/Apartment,₹4200,3.0,2.0,2.0,NaN,2021/12/25
3,IND140,Chennai,Teynampet,Shared Room,"₹1,000",1.0,NaN,1.0,1.0,"May 5, 2022"
4,IND141,Hyderabad,Jubilee Hills,Entire Home/Apartment,3800,3.0,3.0,3.0,5.0,2022-08-20 14:00
5,IND142,Pune,NaN,Private Room,"₹2,500",1.0,1.0,NaN,3.0,10/01/2023
6,IND143,Kolkata,Park Street,Entire Home/Apartment,₹2800,2.0,2.0,2.0,4.0,2022-04-15
7,IND144,Mumbai,Colaba,Shared Room,₹800,1.0,1.0,1.0,NaN,"Jun 18, 2022"
8,IND145,Bangalore,Koramangala,Entire Home/Apartment,₹5200,3.0,3.0,3.0,6.0,2022-02-28
9,IND146,Chennai,Anna Nagar,Private Room,One Thousand Five Hundred,1.0,1.0,1.0,2.0,2022-07-10
10,IND147,Hydrabad,Gachibowli,Entire Home/Apartment,₹4500,3.0,NaN,3.0,4.0,2022-01-10
11,IND148,Mumbai,Andheri,Private Room,₹1200,1.0,1.0,1.0,3.0,"Dec 25, 2021"
12,IND149,Delhi,Dwarka,Shared Room,₹900,1.0,1.0,NaN,2.0,20-Feb-22
13,IND150,Chennai,Egmore,Entire Home/Apartment,₹3800,3.0,3.0,3.0,NaN,11/08/2022
14,IND151,Pune,Shivaji Nagar,Private Room,Two Thousand,1.0,1.0,1.0,4.0,2022-05-15
15,IND152,Kolkata,Camac Street,Entire Home/Apartment,₹3200,2.0,2.0,2.0,5.0,18-Jun-22
16,IND153,Bangalore,Electronic City,Shared Room,₹600,1.0,NaN,1.0,1.0,2022-09-01
17,IND154,Mumbai,Nariman Point,Entire Home/Apartment,₹5800,3.0,3.0,3.0,6.0,2022-03-25 10:00
18,IND155,Hyderabad,Secunderabad,Private Room,₹1000,1.0,1.0,1.0,3.0,"July 4, 2022"
19,IND156,Chennai,Thiruvanmiyur,Entire Home/Apartment,₹4800,3.0,NaN,3.0,5.0,2022-02-14
20,IND157,Mumbai,Worli,Entire Home/Apartment,₹5000,3.0,3.0,NaN,5.0,2022-06-18
21,IND158,Delhi,Aerocity,Private Room,₹1500,1.0,1.0,1.0,4.0,"January 2, 2023"
22,IND159,Bangalore,HSR Layout,Shared Room,₹700,1.0,NaN,1.0,2.0,23-Mar-22
23,IND160,Hyderabad,Kondapur,Entire Home/Apartment,₹4200,3.0,3.0,3.0,6.0,2022-09-15 18:00
24,IND161,Chennai,Velachery,Private Room,Eight Hundred,1.0,1.0,1.0,1.0,10/04/2022
25,IND162,Pune,Koregaon Park,Entire Home/Apartment,₹5800,3.0,3.0,3.0,NaN,2022-07-22
26,IND163,Kolkata,Salt Lake,Shared Room,₹500,1.0,1.0,NaN,2.0,2022-05-01
27,IND164,Mumbai,BKC,Entire Home/Apartment,₹6500,3.0,4.0,4.0,7.0,2022-04-10
28,IND165,Delhi,Saket,Private Room,₹1800,1.0,1.0,1.0,5.0,"August 15, 2022"
29,IND166,Bangalore,MG Road,Entire Home/Apartment,₹7500,3.0,4.0,4.0,NaN,2022-03-28
30,IND167,Chennai,Guindy,Entire Home/Apartment,₹3800,3.0,3.0,NaN,5.0,2022-08-12
31,IND168,Pune,Hadapsar,Private Room,₹1200,1.0,1.0,1.0,3.0,"February 20, 2023"
32,IND169,Kolkata,New Town,Shared Room,₹600,1.0,NaN,1.0,2.0,15-Apr-22
33,IND170,Mumbai,Powai,Entire Home/Apartment,₹5500,3.0,3.0,3.0,6.0,2022-09-20 12:00
34,IND171,Delhi,Rohini,Private Room,One Thousand Five Hundred,1.0,1.0,1.0,4.0,2022-06-01
35,IND172,Bangalore,Jay Nagar,Entire Home/Apartment,₹6800,3.0,4.0,4.0,NaN,2022-04-25
36,IND173,Hyderabad,Manikonda,Shared Room,₹800,1.0,1.0,NaN,3.0,2022-07-15
37,IND174,Chennai,Tambaram,Entire Home/Apartment,₹4500,3.0,3.0,3.0,5.0,2022-03-18
38,IND175,Pune,Wagholi,Private Room,₹1500,1.0,1.0,1.0,4.0,"January 10, 2023"
39,IND176,Kolkata,Baranagar,Entire Home/Apartment,₹5000,3.0,3.0,3.0,NaN,2022-08-05
40,IND177,Mumbai,Ghatkopar,Shared Room,₹700,1.0,NaN,1.0,2.0,22-May-22
41,IND178,Delhi,Dilshad Garden,Entire Home/Apartment,₹6200,3.0,4.0,4.0,7.0,2022-05-12
42,IND179,Bangalore,Electronic City Phase 2,Private Room,₹1800,1.0,1.0,1.0,5.0,"August 25, 2022"
43,IND180,Hyderabad,Kukatpally,Entire Home/Apartment,₹7500,3.0,4.0,4.0,NaN,2022-06-28
44,IND181,Chennai,Adyar,Shared Room,₹500,1.0,1.0,NaN,2.0,2022-04-01
45,IND182,Pune,Bavdhan,Entire Home/Apartment,₹5800,3.0,3.0,3.0,6.0,2022-09-10 18:00
46,IND183,Kolkata,Lake Town,Private Room,₹1200,1.0,1.0,1.0,3.0,"February 15, 2023"
47,IND184,Mumbai,Santacruz,Entire Home/Apartment,₹7000,3.0,4.0,4.0,7.0,2022-07-22
48,IND185,Delhi,Pitampura,Shared Room,Eight Hundred,1.0,NaN,1.0,2.0,10/03/2022
49,IND186,Bangalore,Marathahalli,Entire Home/Apartment,₹8000,3.0,5.0,5.0,NaN,2022-05-05

In [14]:
# Convert PPN column to numeric, handling different formats
df['PPN'] = df['PPN'].astype(str).str.replace('₹', '', regex=False)
df['PPN'] = df['PPN'].str.replace(',', '', regex=False)
df['PPN'] = df['PPN'].str.lower().replace({'one thousand five hundred': '1500',
                                             'two thousand': '2000',
                                             'eight hundred': '800'})
df['PPN'] = pd.to_numeric(df['PPN'], errors='coerce')

In [15]:
df

,ID,City,Location,PType,PPN,Nights,Beds,Baths,Reviews,Recent
0,IND137,Mumbai,NaN,Entire Home/Apartment,3200,2.0,1.0,1.0,4.0,2022-03-12
1,IND138,Bangalor,Indiranagar,Private Room,1800,NaN,1.0,1.0,2.0,15-Feb-23
2,IND139,Delhi,Hauz Khas,Entire Home/Apartment,4200,3.0,2.0,2.0,NaN,2021/12/25
3,IND140,Chennai,Teynampet,Shared Room,1000,1.0,NaN,1.0,1.0,"May 5, 2022"
4,IND141,Hyderabad,Jubilee Hills,Entire Home/Apartment,3800,3.0,3.0,3.0,5.0,2022-08-20 14:00
5,IND142,Pune,NaN,Private Room,2500,1.0,1.0,NaN,3.0,10/01/2023
6,IND143,Kolkata,Park Street,Entire Home/Apartment,2800,2.0,2.0,2.0,4.0,2022-04-15
7,IND144,Mumbai,Colaba,Shared Room,800,1.0,1.0,1.0,NaN,"Jun 18, 2022"
8,IND145,Bangalore,Koramangala,Entire Home/Apartment,5200,3.0,3.0,3.0,6.0,2022-02-28
9,IND146,Chennai,Anna Nagar,Private Room,1500,1.0,1.0,1.0,2.0,2022-07-10
10,IND147,Hydrabad,Gachibowli,Entire Home/Apartment,4500,3.0,NaN,3.0,4.0,2022-01-10
11,IND148,Mumbai,Andheri,Private Room,1200,1.0,1.0,1.0,3.0,"Dec 25, 2021"
12,IND149,Delhi,Dwarka,Shared Room,900,1.0,1.0,NaN,2.0,20-Feb-22
13,IND150,Chennai,Egmore,Entire Home/Apartment,3800,3.0,3.0,3.0,NaN,11/08/2022
14,IND151,Pune,Shivaji Nagar,Private Room,2000,1.0,1.0,1.0,4.0,2022-05-15
15,IND152,Kolkata,Camac Street,Entire Home/Apartment,3200,2.0,2.0,2.0,5.0,18-Jun-22
16,IND153,Bangalore,Electronic City,Shared Room,600,1.0,NaN,1.0,1.0,2022-09-01
17,IND154,Mumbai,Nariman Point,Entire Home/Apartment,5800,3.0,3.0,3.0,6.0,2022-03-25 10:00
18,IND155,Hyderabad,Secunderabad,Private Room,1000,1.0,1.0,1.0,3.0,"July 4, 2022"
19,IND156,Chennai,Thiruvanmiyur,Entire Home/Apartment,4800,3.0,NaN,3.0,5.0,2022-02-14
20,IND157,Mumbai,Worli,Entire Home/Apartment,5000,3.0,3.0,NaN,5.0,2022-06-18
21,IND158,Delhi,Aerocity,Private Room,1500,1.0,1.0,1.0,4.0,"January 2, 2023"
22,IND159,Bangalore,HSR Layout,Shared Room,700,1.0,NaN,1.0,2.0,23-Mar-22
23,IND160,Hyderabad,Kondapur,Entire Home/Apartment,4200,3.0,3.0,3.0,6.0,2022-09-15 18:00
24,IND161,Chennai,Velachery,Private Room,800,1.0,1.0,1.0,1.0,10/04/2022
25,IND162,Pune,Koregaon Park,Entire Home/Apartment,5800,3.0,3.0,3.0,NaN,2022-07-22
26,IND163,Kolkata,Salt Lake,Shared Room,500,1.0,1.0,NaN,2.0,2022-05-01
27,IND164,Mumbai,BKC,Entire Home/Apartment,6500,3.0,4.0,4.0,7.0,2022-04-10
28,IND165,Delhi,Saket,Private Room,1800,1.0,1.0,1.0,5.0,"August 15, 2022"
29,IND166,Bangalore,MG Road,Entire Home/Apartment,7500,3.0,4.0,4.0,NaN,2022-03-28
30,IND167,Chennai,Guindy,Entire Home/Apartment,3800,3.0,3.0,NaN,5.0,2022-08-12
31,IND168,Pune,Hadapsar,Private Room,1200,1.0,1.0,1.0,3.0,"February 20, 2023"
32,IND169,Kolkata,New Town,Shared Room,600,1.0,NaN,1.0,2.0,15-Apr-22
33,IND170,Mumbai,Powai,Entire Home/Apartment,5500,3.0,3.0,3.0,6.0,2022-09-20 12:00
34,IND171,Delhi,Rohini,Private Room,1500,1.0,1.0,1.0,4.0,2022-06-01
35,IND172,Bangalore,Jay Nagar,Entire Home/Apartment,6800,3.0,4.0,4.0,NaN,2022-04-25
36,IND173,Hyderabad,Manikonda,Shared Room,800,1.0,1.0,NaN,3.0,2022-07-15
37,IND174,Chennai,Tambaram,Entire Home/Apartment,4500,3.0,3.0,3.0,5.0,2022-03-18
38,IND175,Pune,Wagholi,Private Room,1500,1.0,1.0,1.0,4.0,"January 10, 2023"
39,IND176,Kolkata,Baranagar,Entire Home/Apartment,5000,3.0,3.0,3.0,NaN,2022-08-05
40,IND177,Mumbai,Ghatkopar,Shared Room,700,1.0,NaN,1.0,2.0,22-May-22
41,IND178,Delhi,Dilshad Garden,Entire Home/Apartment,6200,3.0,4.0,4.0,7.0,2022-05-12
42,IND179,Bangalore,Electronic City Phase 2,Private Room,1800,1.0,1.0,1.0,5.0,"August 25, 2022"
43,IND180,Hyderabad,Kukatpally,Entire Home/Apartment,7500,3.0,4.0,4.0,NaN,2022-06-28
44,IND181,Chennai,Adyar,Shared Room,500,1.0,1.0,NaN,2.0,2022-04-01
45,IND182,Pune,Bavdhan,Entire Home/Apartment,5800,3.0,3.0,3.0,6.0,2022-09-10 18:00
46,IND183,Kolkata,Lake Town,Private Room,1200,1.0,1.0,1.0,3.0,"February 15, 2023"
47,IND184,Mumbai,Santacruz,Entire Home/Apartment,7000,3.0,4.0,4.0,7.0,2022-07-22
48,IND185,Delhi,Pitampura,Shared Room,800,1.0,NaN,1.0,2.0,10/03/2022
49,IND186,Bangalore,Marathahalli,Entire Home/Apartment,8000,3.0,5.0,5.0,NaN,2022-05-05

In [16]:

# Standardize city names
# Standardize city names
df['City'] = df['City'].replace({'Hydrabad': 'Hyderabad', 'Bangalor': 'Bangalore', 'Delhi ': 'Delhi'})

df

,ID,City,Location,PType,PPN,Nights,Beds,Baths,Reviews,Recent
0,IND137,Mumbai,NaN,Entire Home/Apartment,3200,2.0,1.0,1.0,4.0,2022-03-12
1,IND138,Bangalore,Indiranagar,Private Room,1800,NaN,1.0,1.0,2.0,15-Feb-23
2,IND139,Delhi,Hauz Khas,Entire Home/Apartment,4200,3.0,2.0,2.0,NaN,2021/12/25
3,IND140,Chennai,Teynampet,Shared Room,1000,1.0,NaN,1.0,1.0,"May 5, 2022"
4,IND141,Hyderabad,Jubilee Hills,Entire Home/Apartment,3800,3.0,3.0,3.0,5.0,2022-08-20 14:00
5,IND142,Pune,NaN,Private Room,2500,1.0,1.0,NaN,3.0,10/01/2023
6,IND143,Kolkata,Park Street,Entire Home/Apartment,2800,2.0,2.0,2.0,4.0,2022-04-15
7,IND144,Mumbai,Colaba,Shared Room,800,1.0,1.0,1.0,NaN,"Jun 18, 2022"
8,IND145,Bangalore,Koramangala,Entire Home/Apartment,5200,3.0,3.0,3.0,6.0,2022-02-28
9,IND146,Chennai,Anna Nagar,Private Room,1500,1.0,1.0,1.0,2.0,2022-07-10
10,IND147,Hyderabad,Gachibowli,Entire Home/Apartment,4500,3.0,NaN,3.0,4.0,2022-01-10
11,IND148,Mumbai,Andheri,Private Room,1200,1.0,1.0,1.0,3.0,"Dec 25, 2021"
12,IND149,Delhi,Dwarka,Shared Room,900,1.0,1.0,NaN,2.0,20-Feb-22
13,IND150,Chennai,Egmore,Entire Home/Apartment,3800,3.0,3.0,3.0,NaN,11/08/2022
14,IND151,Pune,Shivaji Nagar,Private Room,2000,1.0,1.0,1.0,4.0,2022-05-15
15,IND152,Kolkata,Camac Street,Entire Home/Apartment,3200,2.0,2.0,2.0,5.0,18-Jun-22
16,IND153,Bangalore,Electronic City,Shared Room,600,1.0,NaN,1.0,1.0,2022-09-01
17,IND154,Mumbai,Nariman Point,Entire Home/Apartment,5800,3.0,3.0,3.0,6.0,2022-03-25 10:00
18,IND155,Hyderabad,Secunderabad,Private Room,1000,1.0,1.0,1.0,3.0,"July 4, 2022"
19,IND156,Chennai,Thiruvanmiyur,Entire Home/Apartment,4800,3.0,NaN,3.0,5.0,2022-02-14
20,IND157,Mumbai,Worli,Entire Home/Apartment,5000,3.0,3.0,NaN,5.0,2022-06-18
21,IND158,Delhi,Aerocity,Private Room,1500,1.0,1.0,1.0,4.0,"January 2, 2023"
22,IND159,Bangalore,HSR Layout,Shared Room,700,1.0,NaN,1.0,2.0,23-Mar-22
23,IND160,Hyderabad,Kondapur,Entire Home/Apartment,4200,3.0,3.0,3.0,6.0,2022-09-15 18:00
24,IND161,Chennai,Velachery,Private Room,800,1.0,1.0,1.0,1.0,10/04/2022
25,IND162,Pune,Koregaon Park,Entire Home/Apartment,5800,3.0,3.0,3.0,NaN,2022-07-22
26,IND163,Kolkata,Salt Lake,Shared Room,500,1.0,1.0,NaN,2.0,2022-05-01
27,IND164,Mumbai,BKC,Entire Home/Apartment,6500,3.0,4.0,4.0,7.0,2022-04-10
28,IND165,Delhi,Saket,Private Room,1800,1.0,1.0,1.0,5.0,"August 15, 2022"
29,IND166,Bangalore,MG Road,Entire Home/Apartment,7500,3.0,4.0,4.0,NaN,2022-03-28
30,IND167,Chennai,Guindy,Entire Home/Apartment,3800,3.0,3.0,NaN,5.0,2022-08-12
31,IND168,Pune,Hadapsar,Private Room,1200,1.0,1.0,1.0,3.0,"February 20, 2023"
32,IND169,Kolkata,New Town,Shared Room,600,1.0,NaN,1.0,2.0,15-Apr-22
33,IND170,Mumbai,Powai,Entire Home/Apartment,5500,3.0,3.0,3.0,6.0,2022-09-20 12:00
34,IND171,Delhi,Rohini,Private Room,1500,1.0,1.0,1.0,4.0,2022-06-01
35,IND172,Bangalore,Jay Nagar,Entire Home/Apartment,6800,3.0,4.0,4.0,NaN,2022-04-25
36,IND173,Hyderabad,Manikonda,Shared Room,800,1.0,1.0,NaN,3.0,2022-07-15
37,IND174,Chennai,Tambaram,Entire Home/Apartment,4500,3.0,3.0,3.0,5.0,2022-03-18
38,IND175,Pune,Wagholi,Private Room,1500,1.0,1.0,1.0,4.0,"January 10, 2023"
39,IND176,Kolkata,Baranagar,Entire Home/Apartment,5000,3.0,3.0,3.0,NaN,2022-08-05
40,IND177,Mumbai,Ghatkopar,Shared Room,700,1.0,NaN,1.0,2.0,22-May-22
41,IND178,Delhi,Dilshad Garden,Entire Home/Apartment,6200,3.0,4.0,4.0,7.0,2022-05-12
42,IND179,Bangalore,Electronic City Phase 2,Private Room,1800,1.0,1.0,1.0,5.0,"August 25, 2022"
43,IND180,Hyderabad,Kukatpally,Entire Home/Apartment,7500,3.0,4.0,4.0,NaN,2022-06-28
44,IND181,Chennai,Adyar,Shared Room,500,1.0,1.0,NaN,2.0,2022-04-01
45,IND182,Pune,Bavdhan,Entire Home/Apartment,5800,3.0,3.0,3.0,6.0,2022-09-10 18:00
46,IND183,Kolkata,Lake Town,Private Room,1200,1.0,1.0,1.0,3.0,"February 15, 2023"
47,IND184,Mumbai,Santacruz,Entire Home/Apartment,7000,3.0,4.0,4.0,7.0,2022-07-22
48,IND185,Delhi,Pitampura,Shared Room,800,1.0,NaN,1.0,2.0,10/03/2022
49,IND186,Bangalore,Marathahalli,Entire Home/Apartment,8000,3.0,5.0,5.0,NaN,2022-05-05

In [17]:
# Export the cleaned dataset to a new CSV file
output_file_path = "cleaned_cap_rooms.csv"  # Change the filename if needed
df.to_csv(output_file_path, index=False)

print(f"File successfully saved as {output_file_path}")

File successfully saved as cleaned_cap_rooms.csv

In [8]:
# Group by city and calculate the average PPN
avg_ppn_per_city = df.groupby('City')['PPN'].mean().reset_index()

In [9]:
print(avg_ppn_per_city)

        City          PPN
0  Bangalore  4050.000000
1    Chennai  2587.500000
2      Delhi  2414.285714
3  Hyderabad  3633.333333
4    Kolkata  2216.666667
5     Mumbai  3966.666667
6       Pune  3133.333333